.gitignore
libbson.h

In Swift 5, `bson_t` is treated as an `OpaquePointer` so we no
longer have type information for its fields. This allows us to
retrieve the `len` field by providing a custom accessor.

Provide local accessor for `bson_t.len`

---

Sources/BSON/BSON.swift
Sources/BSON/BSONValue.swift
Sources/BSON/Document.swift
Sources/BSON/DocumentIterator.swift

Forgot I hadn't included this in the last PR, but this should include enough skeleton to get Neal rolling on SWIFT-841 which is adding support for reading and writing integer types and nested documents.
This is all just copying API sketch from driver/design doc. Where possible I left in existing implementations of methods from the driver.
Also I left out Codable conformance for now / removed `BSONValue`'s inheritance from `Codable`, but I'm going to open a new ticket in the epic about adding that back and copyingover conformances + BSONEncoder and BSONDecoder.

SWIFT-837 Add API sketch required for SWIFT-841

---

Package.resolved
Sources/BSON/BSON.swift
Sources/BSON/BSONDocument.swift
Sources/BSON/BSONDocumentIterator.swift
Sources/BSON/BSONError.swift
Tests/BSONTests/BSONCorpusTests.swift
Tests/BSONTests/BSONDocumentIteratorTests.swift
Tests/BSONTests/DocumentTests.swift

https://jira.mongodb.org/browse/SWIFT-867
https://jira.mongodb.org/browse/SWIFT-868
https://jira.mongodb.org/browse/SWIFT-866
This will make BSONDocument's mutable, this is the work of three tickets of implementing the ability to search and splice a byte buffer to provide Create Update and Delete actions on a document. Since I rolled back the significantly more complex document iterator, the work compacted quite a bit so document validation is also in here. And validation is being tested by the corpus runner

SWIFT-868,SWIFT-867,SWIFT-866: Mutable Valid BSONDocument

---

Sources/BSON/BSONDocument.swift

We use force try in the subscript setter which will check the newer, larger, size constant Int32.max.

SWIFT-892: Fix max BSON size limit to be Int32.max rather than server's default max BSON size

---

Sources/BSON/BSON.swift
Sources/BSON/BSONDecimal128.swift
Tests/BSONTests/BSONCorpusTests.swift

(Finally _amiright_)
This adds support to create Decimal128 values from a string and round trip the values to and from BSON.
Note Decimal128.toString is missing right now, this is something that should probably be a part of extJSON work.

SWIFT-840: Decimal 128 Support

---

Sources/BSON/BSONDocument.swift
Sources/BSON/ExtendedJSONEncoder.swift
Tests/BSONTests/ExtendedJSONConversionTests.swift

SWIFT-960
This PR adds support for output formatting options on `ExtendedJSONEncoder` similar to [the ones offered on `JSONEncoder`](https://developer.apple.com/documentation/foundation/jsonencoder/outputformatting).

SWIFT-960 Support outputFormatting options in ExtendedJSONEncoder

---

docs/README.md

This is a very basic landing page for the docs, equivalent to the current landing page for the driver docs. (I'll update that to link to the BSON docs later on.)
I've set up this repo so that it deploys to GitHub pages from the gh-pages branch.
My next step will be to write a documentation generation script which:
- generates the docs based on master
- checks out the gh-pages branch
- commits the doc changes and pushes them to this branch

Add basic landing page README

---

.evergreen/install-tools.sh
Sources/BSON/BSONDecimal128.swift
Sources/BSON/BSONDocumentIterator.swift
Sources/BSON/BSONTimestamp.swift
Sources/BSON/Integers+BSONValue.swift
Sources/BSON/String+BSONValue.swift

I got my new laptop and installed a newer SwiftLint version and found some new violations. It turns out there was a bug in SwiftLint 0.39.2 where the explicit ACL rule was not enforced in extensions.
Testing out docs generation, I also found some places where the missing_docs rule seems to not be enforced so I have added docs where needed.
I will bump the SwiftLint version on the driver as well for consistency.

Bump Swiftlint version and fix violations, add missing docs

---

Guides/BSON.md
etc/docs-main.md
etc/generate-docs.sh

This adds a new script for generating docs via Jazzy. 
As part of this I brought over most of the driver's existing BSON guide. I am thinking we can then cut out most of the driver's guide in the ticket about updating the driver docs, leaving a link to the BSON version of the guide, along with the parts of that guide that are specific to the driver (mainly about using Codable types with collections.)

SWIFT-914 Add docs generation script

---

etc/release.sh

Adds a release script. I haven't run it to completion for obvious reasons but it borrows strongly from the driver's script so I think it will work fine.
In testing this I did accidentally prematurely publish the 3.0 docs (forgot to comment out stuff in that script to commit and push...) but I think that's fine, we aren't linking to it anywhere yet.

SWIFT-937 Add a release script

---

Sources/BSON/BSONDocument.swift
Tests/BSONTests/BSONCorpusTests.swift

It turns out all of the issues we had with these before were fixed by d070d9ca40f0d1a1b479a366f81a087e0733d02a so this just enables the assertions.
I also fixed a couple of error messages missing spaces that I happened to notice.

SWIFT-968 Enable Decimal128 parseError assertion

---

Sources/SwiftBSON/BSONBinary.swift
Sources/SwiftBSON/BSONDocument+Collection.swift
Sources/SwiftBSON/BSONDocument.swift
Sources/SwiftBSON/BSONDocumentIterator.swift
Sources/SwiftBSON/BSONTimestamp.swift
Tests/SwiftBSONTests/BSONDocument+SequenceTests.swift
Tests/SwiftBSONTests/BSONDocumentIteratorTests.swift

SWIFT-935
This PR fixes a few API breakages detected via `swift api-digestor` (via [this script](https://github.com/apple/swift-nio/blob/master/scripts/check_no_api_breakages.sh) from SwiftNIO).
The changes are as following:
- switch `BSONDocumentIterator` back to a `class` (was a `struct`)
- add missing initializer to `BSONTimestamp` (SWIFT-999)
- add missing `Codable` conformance to `BSONBinary.Subtype`
Since `swift api-digester` doesn't recognize `@_exported` types, I manually copied over the entirety of `swift-bson` into the driver and ran it instead. The branch for that is [here](https://github.com/patrickfreed/mongo-swift-driver/tree/drop-in-swift-bson) if you want to try it out yourself. It's based off of the `SWIFT-936/new-bson-library` branch on this repository.
The script is …

SWIFT-935 Fix API breakages from old BSON library

---

.evergreen/config.yml

Adds 5.3 testing to the BSON library.
Evg patch https://spruce.mongodb.com/version/5f6e274fe3c331720a71e3ec/tasks

SWIFT-1010 Test Swift 5.3 on Linux

---

.swiftlint.yml
Sources/SwiftBSON/BSONDocument.swift
Tests/SwiftBSONTests/DocumentTests.swift

This adds a `withID()` method to `BSONDocument` and does a bit of internal refactoring.
Runtime comparisons for relevant benchmarks:
| Benchmark                        | Old   | With SWIFT-1015 | With this fix |
|----------------------------------|-------|-----------------|---------------|
| Small doc bulk insert 10k copies | .096  | 0.424           | 0.116         |
| Large doc bulk insert 10 copies  | 0.332 | 2.79            | 0.352         |
| small doc insertOne 10k times    | 3.258 | 4.481           | 4.021         |
| large doc insertOne 10 times     | 0.327 | 2.812           | 0.326         |

SWIFT-1016 Add a public withID() method

---

Sources/SwiftBSON/BSONBinary.swift
Sources/SwiftBSON/BSONDocument+Sequence.swift
Sources/SwiftBSON/BSONDocument.swift
Sources/SwiftBSON/BSONDocumentIterator.swift
Sources/SwiftBSON/ByteBuffer+BSON.swift
Sources/SwiftBSON/ExtendedJSONEncoder.swift
Tests/SwiftBSONTests/BSONDocumentIteratorTests.swift
Tests/SwiftBSONTests/ExtendedJSONConversionTests.swift

SWIFT-1044
This PR implements a number of improvements to extended JSON generation as laid out in the design doc. Most of the code changes ended up being the original iterator improvements you wrote a while back.
benchmark results (in seconds median execution time):
|             | flat_bson | deep_bson | full_bson |
|-------------|-----------|-----------|-----------|
| libbson     |       2.0 |       0.8 |       1.2 |
| unoptimized |      31.5 |     207.6 |      46.6 |
| target      |       8.0 |       3.2 |       4.6 |
| optimized   |       3.2 |       2.5 |       4.2 |

SWIFT-1044 Improve BSON to JSON performance

---

Sources/SwiftBSON/Array+BSONValue.swift
Sources/SwiftBSON/BSON.swift
Sources/SwiftBSON/BSONCode.swift
Sources/SwiftBSON/BSONDecoder.swift
Sources/SwiftBSON/BSONDocument+Sequence.swift
Sources/SwiftBSON/BSONDocument.swift
Sources/SwiftBSON/BSONEncoder.swift
Sources/SwiftBSON/BSONValue.swift
Sources/SwiftBSON/ExtendedJSONDecoder.swift

SWIFT-1070
This PR improves the performance of the `BSONDecoder`. The goal of this PR is simply to match the libbson-based BSON library's performance, so there are still more possible improvements to be done in the future.
We actually ended up improving upon the existing libbson-based `BSONDecoder` pretty significantly:
| benchmark | libbson based median time | target time (1.25x) | post-optimizations |
|-----------|---------------------------|------------------|--------------------|
| flat BSON | 6.002                     | 7.503            | 2.072              |
| deep BSON | 3.463                     | 4.329            | 2.683              |
| full BSON | 3.876                     | 4.845            | 2.017              |
We also improved upon the improved Native to BSON benchmarks we …

SWIFT-1070 Improve performance of BSONDecoder

---

Sources/SwiftBSON/BSONDocument.swift
Sources/SwiftBSON/BSONDocumentIterator.swift
Sources/SwiftBSON/ExtendedJSONDecoder.swift
Tests/SwiftBSONTests/BSONCorpusTests.swift
Tests/SwiftBSONTests/BSONDocumentIteratorTests.swift
Tests/SwiftBSONTests/DocumentTests.swift

SWIFT-1072
This PR includes the BSON library portion of the insertion improvements. A subsequent PR on the driver repo will be opened after this one goes through.
| benchmark             | libbson based median time | target time (4x) | unoptimized swift-bson | post-optimizations |
|-----------------------|---------------------------|------------------|------------------------|--------------------|
| small doc bulk insert | 0.096                     | 0.12             | 4258.673               | 0.117              |
| large doc bulk insert | 0.332                     | 0.415            | 59.637                 | 0.454              |
| small doc insertOne   | 3.258                     | 4.0725           | 8.276                  | 3.412              |
| large doc insertOne   | 0.327 …

SWIFT-1072 Improve insertion performance

---

Sources/SwiftBSON/BSON.swift
Sources/SwiftBSON/BSONDocument.swift
Tests/SwiftBSONTests/DocumentTests.swift

SWIFT-1086 Ignore key order in array-nested documents in equalsIgnoreKeyOrder

---

Sources/SwiftBSON/ExtendedJSONDecoder.swift
Sources/SwiftBSON/ExtendedJSONEncoder.swift
Tests/SwiftBSONTests/ExtendedJSONConversionTests.swift

SWIFT-1088
This PR adds APIs to `ExtendedJSONEncoder` and `ExtendedJSONDecoder` which utilize NIO's `ByteBuffer` instead of Foundation's `Data`. This can help reduce needless copies when using `ByteBuffer` that would otherwise be required when routing through `Data`.

SWIFT-1088 ByteBuffer extJSON interoperability

---

etc/docs-main.md
etc/generate-docs.sh
etc/release.sh

SWIFT-734
`swift-bson` equivalent of https://github.com/mongodb/mongo-swift-driver/pull/601, though this one does not erroneously commit `update-index.py`.

SWIFT-734 Update scripts to maintain multiple versions of the documentation

---

Guides/JSON-Interop.md
README.md
etc/docs-main.md
etc/release.sh

SWIFT-992
In preparation for renaming the default branch of this repository from `master` to `main`, this PR updates any existing references to the `master` branch accordingly.
I'm planning on just using the GitHub UI to rename the branch instead of creating a new one and then deleting the old one, if that's okay. See: https://github.com/github/renaming

SWIFT-992 Update references to master branch

---

Guides/JSON-Interop.md

Updates the JSON interop guide to reflect that users no longer need to add `ContentEncoder`/`ContentDecoder` conformances themselves.

Update JSON interop guide to reflect Vapor integration

---

Sources/SwiftBSON/BSON.swift
Sources/SwiftBSON/BSONBinary.swift
Sources/SwiftBSON/BSONEncoder.swift
Sources/SwiftBSON/BSONError.swift
Sources/SwiftBSON/BSONRegularExpression.swift
Sources/SwiftBSON/BSONValue.swift
Sources/SwiftBSON/Date+BSONValue.swift
Sources/SwiftBSON/ExtendedJSONDecoder.swift
Sources/SwiftBSON/JSON.swift
Tests/SwiftBSONTests/BSONCorpusTests.swift
Tests/SwiftBSONTests/BSONValueTests.swift
Tests/SwiftBSONTests/CommonTestUtils.swift
Tests/SwiftBSONTests/ExtendedJSONConversionTests.swift

SWIFT-1126 / SWIFT-1137
This PR adds support for legacy extended JSON v1 parsing, which the old libbson-based BSON library had support for. This PR also fixes potential crashes that may occur when trying to use `Date` values extremely far in the future (> `Int64.max` ms from epoch) or the past (< `Int64.min` ms before epoch).

SWIFT-1126 / SWIFT-1137 Add legacy extended JSON parsing, fix Date-related crashes

---

Tests/Specs/bson-corpus/dbref.json
Tests/Specs/bson-corpus/document.json
Tests/Specs/bson-corpus/top.json
Tests/SwiftBSONTests/BSONCorpusTests.swift

* Sync BSON corpus test changes made as part of the "Mitigate pain of using field names with dots and dollars" project (SWIFT-1107)
* I noticed that SWIFT-963 seems to be "gone away" as the tests all pass; so added SWIFT-964 assertions to round trip degenerate BSON through native types

SWIFT-1107, SWIFT-964: BSON corpus test updates

---

.evergreen/config.yml
.evergreen/install-tools.sh
.evergreen/run-tests.sh
Tests/SwiftBSONTests/LeakCheckTests.swift

* Test on Ubuntu 20.04 rather than 16.04
* Test on macOS 10.15 rather than 10.14
* Add testing on Swift 5.4 and 5.5-dev
* Add TSan task
* bump Swift version used for format/lint and bump SwiftLint version accordingly

SWIFT-871, SWIFT-1340: Evergreen config updates

---

Sources/SwiftBSON/BSONEncoder.swift
Sources/SwiftBSON/BSONValue.swift

This is the way this code should have been in the first place, I think 🙂
Previously, we used the `BSONValue` protocol as the intermediate representation of data types stored in the encoder before the final conversion to BSON. However, the only requirement we actually needed from the protocol was the `.bson` property. 
As a result, our internal data structures `MutableDictionary` and `MutableArray` had to conform to `BSONValue`.
This refactor introduces a new `BSONRepresentable` profile that is used throughout the encoder in place of `BSONValue` that actually expresses what we need for encoding purposes - the ability for a type to be converted to BSON.
This is a precursor to work to fix the null bytes issue, will expand in comments.

Decouple BSONEncoder internals from BSONValue protocol

---

Package.resolved
Package.swift
Sources/SwiftBSON/BSON.swift
Sources/SwiftBSON/BSONDocument.swift
Sources/SwiftBSON/BSONDocumentIterator.swift
Sources/SwiftBSON/BSONEncoder.swift
Sources/SwiftBSON/BSONRegularExpression.swift
Sources/SwiftBSON/BSONValue.swift
Sources/SwiftBSON/ByteBuffer+BSON.swift
Sources/SwiftBSON/ExtendedJSONDecoder.swift
Tests/Specs/bson-corpus/code.json
Tests/Specs/bson-corpus/document.json
Tests/Specs/bson-corpus/regex.json
Tests/Specs/bson-corpus/symbol.json
Tests/Specs/bson-corpus/top.json
Tests/SwiftBSONTests/BSONCorpusTests.swift

I did some more re-running of the benchmarks and got the following results:
* JSON to BSON: flat ~5% slower; deep ~7% slower; full  ~10% slower, multi-import ~8% slower
* native to BSON: flat no change, deep ~10% slower, full no change
* runCommand, findOne, insertOne varied across runs, occasionally getting both faster and slower with differences in the range of 1-3%...
For some other benchmarks which do not even touch the new `isValidCString` code, I actually saw both slight speedups and slight slowdowns (like <= 5% change)... I think those can probably just be chalked up to inconsistency on the spawn hosts. 
These numbers do not sound great, but revisiting the scope for the recent BSON performance project, compared to the scope of the performance hits we accepted there (300% slower for …

SWIFT-1260 Disallow embedded null bytes in BSON keys

---

Package.swift
Tests/SwiftBSONTests/BSONTests.swift
Tests/SwiftBSONTests/LeakCheckTests.swift

These changes allow the library to build and tested on iOS, either directly in Xcode or from the command line using `xcodebuild`.

Make necessary changes to build and test the library on iOS

---

.github/workflows/ios.yml
Package.swift

Sets the minimum iOS version for the library to iOS 13, and updates our GH Actions workflow to test on each supported iOS version.
The updated workflow file here applies to what was run for this PR, so you can see the generated tasks that way.
To choose the exact Xcode versions I referenced this [documentation](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#installed-sdks) which shows which iOS simulators are available with each Xcode version, and just went with the latest Xcode + latest iOS patch for each of iOS 13, 14, and 15. 
This implicitly has us test with the corresponding Swift versions that shipped with each of those Xcode versions, which is 5.5.2, 5.4.2, and 5.2.4 respectively. 
From a brief survey of other libraries supporting iOS …

SWIFT-1500, SWIFT-1501: Set minimum iOS version and expand iOS testing

---

Sources/SwiftBSON/BSONRegularExpression.swift

SWIFT-1528
Modifies the String initializer with a default value of empty string for the options parameter

SWIFT-1528 Omitting Options for `BSONRegularExpression`

---

.evergreen/config.yml
.evergreen/configure-swift.sh
.evergreen/get_latest_swift_patch.py
.evergreen/run-tests.sh
Package.swift

SWIFT-1337
Drops Swift 5.1 support. This is a prerequisite for #85
[patch](https://spruce.mongodb.com/version/62fe7e11e3c33116292cca3b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SWIFT-1337 drop Swift 5.1 support 
